### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by kalimer0x00**
- client secrets are not base64 encoded anymore : added a full urlencoding support
- File output wasn't working : fixed

### CODE REVIEW

**Comment by furiel** [comment]
Thanks for this PR, especially for the urlencode part. That looks very interesting.

I have only one comment that might worth integrate: as now graylog is optional, it would worth putting a condition for `self._graylog_interface.start()` and `stop()` too. The start() starts a thread and runs a busy loop, that does nothing when graylog is disabled, taking unnecessary cpu resource.

**Comment by kalimer0x00** [comment]
You are totally right
In a rush, I made quick and dirty fixes to make this work. I didn't have time to analyze the graylog output
Thumbs up for your PR, nice job

**Comment by ddbnl** [comment]
Very late reply as I was away for a while. 

I intregrated the "New urlencoding for client_secret" fix in the latest commit (beafb63). Outputting to file and not starting Graylog output when not required were fixed in the commit before that.

**Comment by ddbnl** [comment]
Very late reply as I was away for a while. 

I intregrated the "New urlencoding for client_secret" fix in the latest commit (beafb63). Outputting to file and not starting Graylog output when not required were fixed in the commit before that.

**Pull request closed without merging**
